### PR TITLE
feat(openshift): Adding migration data to OpenShift, work in progress to test migrations work in OpenShift. NOT READY FOR REVIEW

### PR DESCRIPTION
**Pull request by acoard-aot**
**NOT READY FOR REVIEW YET, OPENING PR TO TRIGGER OPENSHIFT DEPLOY TO TEST OPENSHIFT FUNCTIONALITY**

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-site-registry-143-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-site-registry-143-frontend.apps.silver.devops.gov.bc.ca)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by acoard-aot** [comment]
Closing, will open another, this one's job did not trigger correctly due to opening as draft.

**Comment by acoard-aot** [comment]
Re-opening, trying to trigger Deploy job in `pr-open.yaml`, testing if it loads migration properly.

**Comment by acoard-aot** [comment]
~

**Comment by mishraomp** [comment]
@acoard-aot closing this pr, to make room for other devs to deploy, we can always reopen the pr to have it deployed again.

**Comment by acoard-aot** [comment]
Re-opening to resume testing...

**Comment by acoard-aot** [comment]
GitHub Actions skipped deploy, so closing and re-opening.

**Comment by acoard-aot** [comment]
Closing, will try to deploy in new temporary namespace (now let's see if the pr-close works!, probably not)

**Comment by mishraomp** [comment]
should this now be closed @acoard-aot

**Comment by nikhila-aot** [comment]
closing as this was merged as part of PR159

**Pull request closed without merging**
