### PR TITLE
fix: srs 616

### PR DESCRIPTION
**Pull request by jaspalsingh-aot**
# Description

This PR contains fix for filter pills  and related test cases

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-site-registry-155-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-site-registry-155-frontend.apps.silver.devops.gov.bc.ca)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/merge.yml)

### CODE REVIEW

**Review by anton-bcgov — CHANGES_REQUESTED** [review]
Haven't looked at the code, but I did a quick test and I don't think this is working as intended. And if it is, then the whole experience is very confusing.

https://github.com/user-attachments/assets/8c8b7875-e74a-498e-8dbf-d1d92d6f0a41

**Comment by anton-bcgov** [comment]
As a side note, in the future PRs, please include more detailed descriptions and testing instructions - the default PR template is a good starting point. Screenshots / short demos are also very helpful for the reviewer and for future reference.

**Comment by jaspalsingh-aot** [comment]
> As a side note, in the future PRs, please include more detailed descriptions and testing instructions - the default PR template is a good starting point. Screenshots / short demos are also very helpful for the reviewer and for future reference.

 I appreciate the suggestions regarding more detailed descriptions and testing instructions in future PRs. I’ll make sure to include those, as well as any relevant screenshots or demos.

**Comment by jaspalsingh-aot** [comment]
> Haven't looked at the code, but I did a quick test and I don't think this is working as intended. And if it is, then the whole experience is very confusing.
> 
>  Screen.Recording.2024-11-01.at.7.49.14.PM.mov

I’d like to clarify that this PR primarily focuses on the creation and positioning of the filter pills, as well as their functionality—such as ensuring that deleting a pill removes the corresponding filter. The table results are indeed tied to the API call, and if you check the network, you'll see the request is being sent successfully. Nikhila is handling the response according to the filters in a separate ticket. I hope this provides some clarity!

**Review by anton-bcgov — APPROVED** [review]

**Pull request merged**
