### PR TITLE
feat(cd): Add HELM Charts for deploying to Openshift.   

### PR DESCRIPTION
**Pull request by mishraomp**
TODO: in next PR add, Github Actions code(GHA) to deploy to dev namespace on merge to dev branch.

Goal is to get something going in OpenShift, once it is deployed to OpenShift, need to discuss and finalize if crunchy is preferred and adjust the helm charts accordingly.

### CODE REVIEW

**Review by bolny — APPROVED** [review]
With the caveat that I'm no expert with Helm, based on what I know about openshift and our application everything here seems reasonable, and I don't see anything that is obviously wrong.

**Review by nikhila-aot — COMMENTED** [review]
I'll leave it open for @acoard-aot to have a look before merging

**Comment by mishraomp** [comment]
> I'll leave it open for @acoard-aot to have a look before merging

I will create another PR on top of this to start deploying to openshift namespace

**Comment by mishraomp** [comment]
Closing in favor of https://github.com/bcgov/nr-site-registry/pull/96

**Pull request closed without merging**
