### PR TITLE
fix: Feat/srs 275a

### PR DESCRIPTION
**Pull request by nikhila-aot**
These changes in the entity are required for a successful data migration

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-site-registry-141-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-site-registry-141-frontend.apps.silver.devops.gov.bc.ca)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/merge.yml)

### CODE REVIEW

**Review by acoard-aot — APPROVED** [review]

**Comment by acoard-aot** [comment]
Please do not attempt to merge this yet, even though approved. I will try and deploy db dump to PR environment first as experiment.

**Review by jaspalsingh-aot — APPROVED** [review]
seems fine to me

**Comment by mishraomp** [comment]
converted to draft to make sure it is not merged

**Comment by nikhila-aot** [comment]
closing as its merged as part of PR 159

**Pull request closed without merging**
