### PR TITLE
feat: SRS 275 data migration using ora2pg

### PR DESCRIPTION
**Pull request by nikhila-aot**
This PR will have the changes required to migrate data from Oracle DB to Postgres using the opensource tool ora2pg

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Backend](https://nr-site-registry-116-backend.apps.silver.devops.gov.bc.ca)
- [Frontend](https://nr-site-registry-116-frontend.apps.silver.devops.gov.bc.ca)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-site-registry/actions/workflows/merge.yml)

### CODE REVIEW

**Comment by mishraomp** [comment]
we should look at this Dockerfile, https://github.com/Bluestep-Systems/ora2pg-docker/blob/main/Dockerfile
I would like to avoid putting binaries into GitHub, as they can be downloaded during the build itself,
```
ARG ORAVERSION=21
ARG ORACLIENT_BASIC=https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm
ARG ORACLIENT_DEVEL=https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-devel-21.1.0.0.0-1.x86_64.rpm
ARG ORACLIENT_SQLPLUS=https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-sqlplus-21.1.0.0.0-1.x86_64.rpm
```

**Comment by nikhila-aot** [comment]
> oid putting binaries into GitHub, as they can be downloaded during the build itself,



> we should look at this Dockerfile, https://github.com/Bluestep-Systems/ora2pg-docker/blob/main/Dockerfile I would like to avoid putting binaries into GitHub, as they can be downloaded during the build itself,
> 
> ```
> ARG ORAVERSION=21
> ARG ORACLIENT_BASIC=https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm
> ARG ORACLIENT_DEVEL=https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-devel-21.1.0.0.0-1.x86_64.rpm
> ARG ORACLIENT_SQLPLUS=https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-sqlplus-21.1.0.0.0-1.x86_64.rpm
> ```

I tried the direct download when I started off with this task, but let me take a look at the one you shared

**Comment by mishraomp** [comment]
do we need this to be build and deployed to OpenShift @nikhila-aot ?

**Comment by nikhila-aot** [comment]
> do we need this to be build and deployed to OpenShift @nikhila-aot ?

This is something I highlighted today in the standup, since its a one-time migration, we might not have to get it deployed in the OpenShift environment. However I connect to Oracle over VPN in my local machine to generate the script and I also have a dump of the sql for the Oracle test environment.

**Review by acoard-aot — APPROVED** [review]
lgtm :)

**Pull request merged**
